# Generated by Django 2.2 on 2021-04-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamSpotApp', '0004_auto_20210425_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='response',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
