# Generated by Django 2.2 on 2021-04-27 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamSpotApp', '0006_auto_20210425_1438'),
        ('TeamSpotApp', '0006_auto_20210425_2150'),
    ]

    operations = [
    ]
